name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - run: ls -R .
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "app-latest"
        prerelease: false
        title: Latest Compiled APK
        files: |
          restaurantclient/build/outputs/apk/debug/restaurantclient-debug.apk
          restaurantclient/build/outputs/apk/release/restaurantclient-release-unsigned.apk
          studentclient/build/outputs/apk/debug/studentclient-debug.apk
          studentclient/build/outputs/apk/release/studentclient-release-unsigned.apk
